//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialForseth
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.claims = new HashSet<claim>();
        }
    
        public int id { get; set; }
        public string handle { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<claim> claims { get; set; }
    }
}
