//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialForseth
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim
    {
        public int Id { get; set; }
        public string account { get; set; }
        public string amount { get; set; }
        public string location { get; set; }
        public string approved { get; set; }
    
        public virtual account account1 { get; set; }
    }
}
